---
version: 0.2

phases:

  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - |
        wget -O /usr/local/bin/boot \
          https://github.com/boot-clj/boot-bin/releases/download/2.7.2/boot.sh \
          && chmod ugo+x /usr/local/bin/boot
      - BOOT_AS_ROOT=yes

  build:
    commands:
      - make ${GOAL}

  post_build:
    commands:
      - mkdir codebuild-artifacts
      - |
        if [ "$(echo X$(echo ${CODEBUILD_SOURCE_VERSION} | cut -d '/' -f 1))" = "Xpr" ]; then
          echo "Pull Request build detected; no artifacts will be produced."
          touch codebuild-artifacts/sentinel
        else
          cp target/ssapp.zip codebuild-artifacts
        fi

artifacts:

  base-directory: codebuild-artifacts
  files: ['**/*']
  name: ssapp

cache:
  paths:
    - /root/.m2/**/*
