---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A sinistral (AWS) serverless application.
Transform: AWS::Serverless-2016-10-31

Parameters:

  Stage:
    Type: String
    AllowedValues:
      - test
      - prod

Globals:

  Function:
    Environment:
      Variables:
        DEPLOYMENT_STAGE: !Ref Stage

Resources:

  LambdaFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../target/lambda-deployment-package.zip
      Handler: ssapp.aws.lambda.handler
      MemorySize: 128
      Runtime: nodejs8.10
      Timeout: 10
